name: sunpy-pyspedas-summer-school
channels:
- conda-forge
dependencies:
- python < 3.12
- pip
- hdf5
- pip:
  - aiapy
  - solarmach
  - sunkit-image
  - sunpy[all]
  - sunpy-soar
  - stixpy
  - pyspedas
